#ifndef SPRITES_H
#define SPRITES_H

#include <HyperDisplay_KWH018ST01_4WSPI.h>

// Auto generated by assets/generate.py

extern ILI9163C_color_18_t screenBuffer[128*160];

struct Sprite { int width; int height; int left; int top; const ILI9163C_color_18_t* pixels; };

const extern Sprite sprite_background;
const extern Sprite sprite_sleeping0000;
const extern Sprite sprite_sleeping0060;
const extern Sprite sprite_sleeping0120;
const extern Sprite sprite_woke0000;
#endif
