#ifndef SPRITES_H
#define SPRITES_H

#include <HyperDisplay_KWH018ST01_4WSPI.h>
// Auto generated by assets/generate.py

struct Sprite { uint16_t width; uint16_t height; const ILI9163C_color_18_t* pixels; };

const extern PROGMEM Sprite sprite_no_sd;


#endif
